### ISSUE TITLE
Clarification on Expression Columns in Your Code

### ISSUE THREAD

**Issue by moonyy929** [ArnabKumarRoy02/ResEmoteNet#11]
Hi, Arnab. Thanks for your great work! I would like to ask about the dataset that your code is based on, particularly regarding the expression columns. For example, in the code, the header is defined as class_labels = ['happiness', 'surprise', 'sadness', 'anger', 'disgust', 'fear', 'neutral']. I would like to know which dataset corresponds to these columns.

Thank you!

**Comment by ArnabKumarRoy02** [comment]
Hi @moonyy929, thanks for pointing out the wrong labels. It's been updated. The labels are for all the datasets that have been used in the project: FER2013, RAF-DB, AffectNet-7.
