### ISSUE TITLE
Unable to reproduce promised accuracy for FER2013 dataset even in the best case scenario

### ISSUE THREAD

**Issue by anay-p** [ArnabKumarRoy02/ResEmoteNet#13]
I tried to get just the accuracy figure of 79.79% proposed in the paper for FER2013 dataset but only got 71.57%.

I gave the model the best shot I could by using the model weights provided in the README file ([link](https://drive.google.com/drive/folders/1Daxa6d1-XFxxpg6dyxYl4V-anfiHwtqK?usp=sharing)) and the test dataset provided as a response to issue #12 ([link](https://drive.google.com/file/d/1Dz27LuCuDRnu172LMy82JWmPDr9nO0dD/view)). You can find the code I ran below (adapted from existing code in the repo):

```python
import torch
from torch.utils.data import DataLoader
from torchvision import transforms

from approach.ResEmoteNet import ResEmoteNet
from get_dataset import Four4All

device = torch.device("cuda")
print(f"Using {device} device")

model = ResEmoteNet().to(device)
checkpoint = torch.load('weights\\fer2013_model.pth', weights_only=True)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.Grayscale(num_output_channels=3),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

test_dataset = Four4All(csv_file='dataset\\test_labels.csv',
                        img_dir='dataset\\test', transform=transform)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)
test_image, test_label = next(iter(test_loader))

print(f"Test batch: Image shape {test_image.shape}, Label shape {test_label.shape}")

test_correct = 0
test_total = 0
with torch.no_grad():
    for data in test_loader:
        inputs, labels = data[0].to(device), data[1].to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        test_total += labels.size(0)
        test_correct += (predicted == labels).sum().item()

test_acc = test_correct / test_total

print(f"Test accuracy: {test_acc*100:.2f}%")
```

Output:

```
Using cuda device
Test batch: Image shape torch.Size([16, 3, 64, 64]), Label shape torch.Size([16])
Test accuracy: 71.57%
```

What exactly do I need to do to get the promised accuracy results? Perhaps I'm doing something wrong.

**Comment by ArnabKumarRoy02** [comment]
Hi @anay-p, I didn't find any problem with the way you ran the experiment. But I urge you to just check if you have the latest models and the dataset. That might cause the issue.

Also you can try to run the training from scratch.

**Comment by ArnabKumarRoy02** [comment]
I'm closing this issue for now, feel free to open this if you have further problems.

**Comment by anay-p** [comment]
Hey @ArnabKumarRoy02. I downloaded the latest model and dataset from the links that you provided. I have mentioned the same links above.

I also tried training the model myself by running the code in a Kaggle Notebook with a P100 GPU but I keep getting errors (for context, I'm using `torch.device("cuda")`):
```
RuntimeError: CUDA error: unspecified launch failure
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
In the paper, you have menioned that you had also used Kaggle for training the model. What did you do about these issues?

**Comment by anay-p** [comment]
Also, I think you should reopen this issue as it hasn't really been resolved. I don't see an option to do that from my end as I am not a collaborator in this repository.

**Comment by ArnabKumarRoy02** [comment]
I ran the same script in Kaggle, I didn't seem to have any issues as you
stated. But here is a script that you can use for training.

**Comment by ArnabKumarRoy02** [comment]
Here's the script that was used. You can find it [here](https://drive.google.com/file/d/1sb02BaV4pd-95W4ZaV8-1WoywkVgkf5B/view?usp=sharing). Try with this script. Let me know if you face the same issue again.

**Comment by anay-p** [comment]
This was very generous of you, thank you! This indeed solved the issues. I was able to train the model and get good results.
