### ISSUE TITLE
sorry,but where can i get the dataset? plz

### ISSUE THREAD

**Issue by alanniido** [ArnabKumarRoy02/ResEmoteNet#19]
where can i get the dataset? TT

**Comment by ArnabKumarRoy02** [comment]
We used 4 datasets here:
 - For FER2013, you can get the dataset through Kaggle, or [here's](https://drive.google.com/file/d/1Dz27LuCuDRnu172LMy82JWmPDr9nO0dD/view) the copy we used.
 - For [RAF-DB](http://www.whdeng.cn/RAF/model1.html), you have to request the owner for a copy.
 - Similar to RAF-DB, you have request for a copy of [AffectNet](http://mohammadmahoor.com/affectnet/).
 - For [ExpW](https://www.kaggle.com/datasets/mohammedaaltaha/expwf), you can get it on Kaggle as well.
