### ISSUE TITLE
Please share the link to the Dataset  ( CSV files : train_labels.csv , valid_labels.csv, test_labels.csv )

### ISSUE THREAD

**Issue by savitru10** [ArnabKumarRoy02/ResEmoteNet#24]
Hello Arnab 

Request you to please share the link to Dataset used 
  ( CSV files : train_labels.csv , valid_labels.csv, test_labels.csv )

Thank you!

Best Regards
Sindhu

**Comment by ArnabKumarRoy02** [comment]
Hey @savitru10, I have provided the copy of FER2013 and RAF-DB dataset in #12 and #22. You can check it out there.
