### ISSUE TITLE
Dataset link that you provided is not working anymore

### ISSUE THREAD

**Issue by KhinChoWin-AI** [ArnabKumarRoy02/ResEmoteNet#8]
The complete dataset in the dataset section is not working anymore. Can you please provide other links? Thanks in advance!

![Screenshot from 2024-10-03 19-18-45](https://github.com/user-attachments/assets/703bcf22-353d-4c8e-a00e-7452b253d3b1)

**Comment by ArnabKumarRoy02** [comment]
We have decided not to make that particular dataset public. However, there are numerous other open-source datasets available that you can utilize for your project.
