### ISSUE TITLE
where is the data？

### ISSUE THREAD

**Issue by chengmengxi** [ArnabKumarRoy02/ResEmoteNet#9]
Dear author, 
could you please send us a link to the dataset?
I click on your github data@e484961 and find the status is 404

**Comment by ArnabKumarRoy02** [comment]
We have chosen not to make that specific dataset publicly available. However, there are numerous other open-source datasets that you may utilize for your project.

Should you require that particular dataset, please feel free to contact me via email, and I would be happy to provide you with a copy.

**Comment by chengmengxi** [comment]
Thank you very much for your reply!


I need these particular datasets and would appreciate if you could provide it to me


Thank you again.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ArnabKumarRoy02/ResEmoteNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月20日(星期天) 凌晨3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ArnabKumarRoy02/ResEmoteNet] where is the data？ (Issue #9)





 
We have chosen not to make that specific dataset publicly available. However, there are numerous other open-source datasets that you may utilize for your project.
 
Should you require that particular dataset, please feel free to contact me via email, and I would be happy to provide you with a copy.

**Comment by chengmengxi** [comment]
Hello ArnabKumarRoy,&nbsp;I was very impressed by the work you have done.


&nbsp; Previously, I reached out to you via GitHub, and you kindly suggested that I contact you through email.

&nbsp; In accordance with your guidance, I am writing to request access to the three datasets used in your research: RAF-DB, FER2013, and AffectNet.


&nbsp; Thank you very much for considering my request.&nbsp;I look forward to your response.

&nbsp;&nbsp;My email address is any of the following three:

&nbsp; &nbsp; &nbsp; ***@***.***&nbsp;
&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; ***@***.***

&nbsp; &nbsp; &nbsp; ***@***.***
&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp;Thank you again!
&nbsp; &nbsp; &nbsp;&nbsp;


Best regards,





Mengxi Cheng








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ArnabKumarRoy02/ResEmoteNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月20日(星期天) 凌晨3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ArnabKumarRoy02/ResEmoteNet] where is the data？ (Issue #9)





 
We have chosen not to make that specific dataset publicly available. However, there are numerous other open-source datasets that you may utilize for your project.
 
Should you require that particular dataset, please feel free to contact me via email, and I would be happy to provide you with a copy.

**Comment by ArnabKumarRoy02** [comment]
Hi Mengxi.

I can give you a copy of the FER2013 dataset. You can find it [here](https://www.kaggle.com/datasets/msambare/fer2013). Just follow the procedure given in the repository for preparing the data.

But for RAF-DB and AffectNet, you need to contact their owners of the dataset as I cannot share from my side due to an agreement with them.

I hope you understand this situation.
Good luck.
